# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJXwDAUSseYjifRw_1x2cQulzJDO1co5
"""

!pip install ColabTurtle
from ColabTurtle.Turtle import*

initializeTurtle(initial_speed = 1, initial_window_size=(500,500))
clear()

a=250*3**(1/2)
bgcolor("yellow")
pensize(3)

for i in range(2):
  penup()
  goto(250,250)
  forward(250)
  pendown()
  left(150)
  forward(a)
  left(120)
  forward(a)
  left(120)
  forward(a)
  right(20)

initializeTurtle(initial_speed = 8,
                 initial_window_size=(500,500))
clear()

a=250*3**(1/2)
bgcolor("yellow")
pensize(3)

for i in range(12):
  penup()
  goto(250,250)
  forward(250)
  pendown()
  left(150)
  forward(a)
  left(120)
  forward(a)
  left(120)
  forward(a)
  right(20)